# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BikeCam' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BikeCam

  target 'BikeCam-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'BikeCamTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'BikeCam-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for BikeCam-tvOS

#   target 'BikeCam-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

pod 'Firebase/Core'


